services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pharmacy_frontend
    restart: unless-stopped
    ports:
      - "3001:80"
    networks:
      - pharmacy-network
    environment:
      - REACT_APP_API_URL=/api

networks:
  pharmacy-network:
    external: true

