services:
  frontend:
    image: nginx:alpine
    container_name: pharmacy_frontend
    restart: unless-stopped
    ports:
      - "3001:80"
    volumes:
      - ./dist:/usr/share/nginx/html
    networks:
      - pharmacy-network

networks:
  pharmacy-network:
    external: true
